module(..., package.seeall);

words={}
table.insert(words, "Lorem")
table.insert(words, "ipsum")
table.insert(words, "dolor")
table.insert(words, "sit")
table.insert(words, "amet")
table.insert(words, "consectetur")
table.insert(words, "adipisicing")
table.insert(words, "elit")
table.insert(words, "sed")
table.insert(words, "eiusmod")
table.insert(words, "tempor")
table.insert(words, "incididunt")
table.insert(words, "ut")
table.insert(words, "labore")
table.insert(words, "et")
table.insert(words, "dolore")
table.insert(words, "magna")
table.insert(words, "aliqua")
table.insert(words, "Ut")
table.insert(words, "enim")
table.insert(words, "ad")
table.insert(words, "minim")
table.insert(words, "veniam")
table.insert(words, "quis")
table.insert(words, "nostrud")
table.insert(words, "exercitation")
table.insert(words, "ullamco")
table.insert(words, "laboris")
table.insert(words, "nisi")
table.insert(words, "ut")
table.insert(words, "aliquip")
table.insert(words, "ex")
table.insert(words, "ea")
table.insert(words, "commodo")
table.insert(words, "consequat.")
table.insert(words, "Duis")
table.insert(words, "aute")
table.insert(words, "irure")
table.insert(words, "dolor")
table.insert(words, "in")
table.insert(words, "reprehenderit")
table.insert(words, "in")
table.insert(words, "voluptate")
table.insert(words, "velit")
table.insert(words, "esse")
table.insert(words, "cillum")
table.insert(words, "dolore")
table.insert(words, "eu")
table.insert(words, "fugiat")
table.insert(words, "nulla")
table.insert(words, "pariatur")
table.insert(words, "Excepteur")
table.insert(words, "sint")
table.insert(words, "occaecat")
table.insert(words, "cupidatat")
table.insert(words, "non")
table.insert(words, "proident")
table.insert(words, "sunt")
table.insert(words, "in")
table.insert(words, "culpa")
table.insert(words, "qui")
table.insert(words, "officia")
table.insert(words, "deserunt")
table.insert(words, "mollit")
table.insert(words, "anim")
table.insert(words, "id")
table.insert(words, "est")
table.insert(words, "laborum")

math.randomseed( os.time() ) 

-- returns a random word
function random_word()
   local size = #words
   local i = math.random(size)
   return words[i]
end
